web:
  image: 'smachara2/gitlab:latest'
  restart: always
  hostname: 'cumulus-repo.com'
  environment:
    GITLAB_OMNIBUS_CONFIG: |
      external_url 'https://157.159.232.15/'
  ports:
    - '80:80'
    - '443:443'
    - '22:22'
  volumes:
    - '/srv/gitlab/config:/etc/gitlab'
    - '/srv/gitlab/logs:/var/log/gitlab'
    - '/srv/gitlab/data:/var/opt/gitlab'
